export const GET_OKR_DETAILS = 'GET_OKR_DETAILS';
export const UPDATE_OKR_DETAILS = 'UPDATE_OKR_DETAILS';
export const UPDATE_OKR_CATEGORIES = 'UPDATE_OKR_CATEGORIES';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_MODAL_DATA = 'UPDATE_MODAL_DATA';
export const UPDATE_MODAL_STATUS = 'UPDATE_MODAL_STATUS';